INSERT INTO public."WebAXEL_robotcategory"(categorie) VALUES 
('Adaptable robotics‎'),
('Agricultural robotics‎'),
('Robot architectures‎'),
('Articulated robotics‎'),
('BEAM robotics‎'),
('Biorobotics‎'),
('Cloud robotics‎'),
('Robotics concepts‎'),
('Robot control'),
('Cyborgs'),
('Robotics dogs'),
('Entertainment robotics‎'),
('Robotics events‎'),
('Robotics hardware‎'),
('Robotics hexapod'),
('Health care robotics‎'),
('Home automation‎'),
('Industrial robotics‎'),
('Robotic manipulation‎'),
('Medical robotics'),
('Military robotics‎'),
('Multi-robot systems'),
('Robotic art‎')