# Generated by Django 3.0.1 on 2019-12-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAXEL', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
