# Generated by Django 3.0.1 on 2019-12-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WebAXEL', '0005_auto_20191229_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout du document")),
                ('auteur', models.CharField(blank=True, max_length=255, null=True)),
                ('contenu', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout du document")),
                ('auteur', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='static/img/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
