# Generated by Django 3.0.1 on 2019-12-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAXEL', '0008_document_srcdoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='srcDoc',
            field=models.CharField(max_length=255, null=True, verbose_name='URL Statique'),
        ),
    ]
