# Generated by Django 3.0.1 on 2019-12-30 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAXEL', '0013_auto_20191230_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='srcDoc',
        ),
    ]
