# Generated by Django 3.0.1 on 2019-12-31 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAXEL', '0014_remove_document_srcdoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='nb_vues',
            field=models.IntegerField(default=0, verbose_name='Nombre de vues du document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='auteur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Auteur du document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description du document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(null=True, upload_to='static/docs/', verbose_name='Fichier'),
        ),
    ]
