# Generated by Django 3.0.1 on 2020-01-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAXEL', '0016_auto_20200102_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=255, verbose_name="Catégorie de l'ensemble de données")),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=255, verbose_name='Catégorie du Document')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(null=True, upload_to='static/docs/', verbose_name='Fichier document'),
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout de l'ensemble de données")),
                ('description', models.TextField(blank=True, null=True, verbose_name="Description de l'ensemble de données")),
                ('dataset', models.FileField(null=True, upload_to='static/datasets/', verbose_name='Fichier ensemble de données')),
                ('categories_dataset', models.ManyToManyField(default=None, to='WebAXEL.DataSetCategory', verbose_name="Catégorie de l'ensemble de données")),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='categories_document',
            field=models.ManyToManyField(default=None, to='WebAXEL.DocumentCategory', verbose_name='Catégorie du Document'),
        ),
    ]
