# Generated by Django 3.0.1 on 2020-01-03 22:44

import datetime
import django.contrib.auth.models
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('WebAXEL', '0019_delete_axeladmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='axeluser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='axeluser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='axeluser',
            name='user',
        ),
        migrations.AddField(
            model_name='axeluser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 22, 44, 8, 951325, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='axeluser',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='axeluser',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='axeluser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='axeluser',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='axeluser',
            name='is_staff',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='axeluser',
            name='is_superuser',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='axeluser',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='axeluser',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='axeluser',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='axeluser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='axeluser',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
