# Generated by Django 3.0.1 on 2020-01-03 22:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebAXEL', '0021_auto_20200103_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axeluser',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
