# Generated by Django 3.0.1 on 2020-01-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAXEL', '0028_auto_20200104_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='axeluser',
            name='fonction',
            field=models.CharField(choices=[('Visiteur', 'Guest'), ('Utilisateur', 'User'), ('Développeur', 'Dev'), ('Administrateur Django', 'Djangadmin'), ('Administrateur A.X.E.L.', 'Axeladmin')], default='Visiteur', max_length=100),
        ),
        migrations.AlterField(
            model_name='axeluser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
