# Generated by Django 3.0.1 on 2020-01-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAXEL', '0031_auto_20200104_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axeluser',
            name='fonction',
            field=models.CharField(choices=[('Visiteur', 'Guest'), ('Utilisateur', 'User'), ('Développeur', 'Dev'), ('Administrateur Django', 'Djangadmin'), ('Administrateur A.X.E.L.', 'Axeladmin'), ('Super Administrateur', 'Superadmin')], default='Visiteur', max_length=100),
        ),
    ]
