# Generated by Django 3.0.1 on 2020-01-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAXEL', '0037_auto_20200106_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axeluser',
            name='fonction',
            field=models.CharField(choices=[('Visiteur', 'Guest'), ('Utilisateur', 'User'), ('Développeur', 'Dev'), ('Administrateur Django', 'Djangadmin'), ('Administrateur A.X.E.L.', 'Axeladmin'), ('Super Administrateur', 'Superadmin')], default='Visiteur', max_length=100, verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='axeluser',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='static/img/profilesImages/', verbose_name='Image Profil'),
        ),
        migrations.AlterField(
            model_name='axeluser',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name="Nom d'utilisateur"),
        ),
    ]
