# Generated by Django 3.0.1 on 2020-01-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAXEL', '0039_dataset_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='source',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Source'),
        ),
    ]
