# Generated by Django 3.0.1 on 2020-01-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAXEL', '0040_auto_20200107_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='categories_dataset',
            field=models.ManyToManyField(blank=True, to='WebAXEL.DataSetCategory', verbose_name="Catégorie de l'ensemble de données"),
        ),
    ]
