# Generated by Django 3.0.1 on 2020-01-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAXEL', '0044_auto_20200107_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='categories_document',
        ),
        migrations.AddField(
            model_name='document',
            name='categories_document',
            field=models.ManyToManyField(blank=True, default=None, to='WebAXEL.DocumentCategory', verbose_name='Catégorie du Document'),
        ),
    ]
