# Generated by Django 3.0.1 on 2020-01-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAXEL', '0048_auto_20200108_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='doc',
            field=models.FileField(null=True, upload_to='static/robots/', verbose_name='Documentation Robot'),
        ),
    ]
