# Generated by Django 3.0.1 on 2020-01-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAXEL', '0049_robot_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='categories_robot',
            field=models.ManyToManyField(blank=True, default=None, to='WebAXEL.RobotCategory', verbose_name='Catégories du robot'),
        ),
    ]
