# Generated by Django 3.0.1 on 2020-01-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAXEL', '0051_robot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='utilisation',
            field=models.CharField(max_length=1000, verbose_name='Utilisation'),
        ),
    ]
