# Generated by Django 3.0.1 on 2019-12-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminAXEL', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
