# Generated by Django 3.0.1 on 2019-12-29 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAXEL', '0004_auto_20191228_1611'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
