# Generated by Django 3.0.1 on 2019-12-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAXEL', '0007_auto_20191229_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='srcDoc',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
    ]
