# Generated by Django 3.0.1 on 2020-01-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAXEL', '0015_auto_20191231_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
    ]
