# Generated by Django 3.0.1 on 2020-01-03 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAXEL', '0018_axeladmin_axeluser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AxelAdmin',
        ),
    ]
