# Generated by Django 3.0.1 on 2020-01-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAXEL', '0023_auto_20200104_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axeluser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
