# Generated by Django 3.0.1 on 2020-01-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAXEL', '0032_auto_20200104_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='axeluser',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
