# Generated by Django 3.0.1 on 2020-01-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAXEL', '0035_auto_20200104_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axeluser',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='static/img/profilesImages/'),
        ),
    ]
