# Generated by Django 3.0.1 on 2020-01-07 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebAXEL', '0042_auto_20200107_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='categories_dataset',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='WebAXEL.DataSetCategory', verbose_name="Catégorie de l'ensemble de données"),
        ),
        migrations.AlterField(
            model_name='document',
            name='categories_document',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='WebAXEL.DocumentCategory', verbose_name='Catégorie du Document'),
        ),
    ]
