# Generated by Django 3.0.1 on 2020-01-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAXEL', '0047_auto_20200107_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=255, verbose_name='Catégorie du robot')),
            ],
        ),
        migrations.AlterField(
            model_name='dataset',
            name='categories_dataset',
            field=models.ManyToManyField(blank=True, default=None, to='WebAXEL.DataSetCategory', verbose_name='Catégories du jeu de données'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset',
            field=models.FileField(null=True, upload_to='static/datasets/', verbose_name='Fichier jeu de données'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout du jeu de données"),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description du jeu de données'),
        ),
        migrations.AlterField(
            model_name='datasetcategory',
            name='categorie',
            field=models.CharField(max_length=255, verbose_name='Catégorie du jeu de données'),
        ),
        migrations.AlterField(
            model_name='document',
            name='categories_document',
            field=models.ManyToManyField(blank=True, default=None, to='WebAXEL.DocumentCategory', verbose_name='Catégories du Document'),
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('model', models.CharField(max_length=255, verbose_name='Modèle')),
                ('utilisation', models.CharField(max_length=255, verbose_name='Utilisation')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout du robot")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description du robot')),
                ('categories_robot', models.ManyToManyField(blank=True, default=None, to='WebAXEL.DataSetCategory', verbose_name='Catégories du robot')),
            ],
        ),
    ]
