# Generated by Django 3.0.1 on 2020-01-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAXEL', '0050_auto_20200108_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/img/robots', verbose_name='Image Robot'),
        ),
    ]
