# Generated by Django 3.0.2 on 2020-01-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAXEL', '0052_auto_20200109_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='nb_vues',
            field=models.IntegerField(default=0, verbose_name='Nombre de vues du jeu de données'),
        ),
        migrations.AddField(
            model_name='robot',
            name='nb_vues',
            field=models.IntegerField(default=0, verbose_name='Nombre de vues du robot'),
        ),
    ]
