# Generated by Django 3.0.2 on 2020-01-25 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=None, max_length=100, verbose_name="Nom de l'arme")),
                ('prix', models.IntegerField(blank=True, default=None, null=True, verbose_name="Prix de l'arme")),
                ('type_armure', models.CharField(choices=[('1', 'Armes courantes de corps à corps'), ('2', 'Armes courantes à distance'), ('3', 'Armes de guerre de corps à corps'), ('4', 'Armes de guerre à distance')], default=None, max_length=100, verbose_name="Type de l'arme")),
                ('degat', models.IntegerField(default=1)),
                ('poids', models.IntegerField(blank=True, default=None, null=True, verbose_name="Poids de l'arme en kilogrammes")),
                ('proprietes', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name="Propriétés de l'arme")),
            ],
        ),
        migrations.CreateModel(
            name='Armure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=None, max_length=100, verbose_name="Nom de l'armure")),
                ('prix', models.IntegerField(blank=True, default=None, null=True, verbose_name="Prix de l'armure")),
                ('type_armure', models.CharField(choices=[('1', 'Armure légère'), ('2', 'Armure intermédiaire'), ('3', 'Armure lourde')], default=None, max_length=100, verbose_name="Type de l'armure")),
                ('ca_bonus', models.IntegerField(blank=True, default=None, null=True, verbose_name='CA Bonus')),
                ('max_dex', models.IntegerField(blank=True, default=None, null=True, verbose_name='Maximum Dextérité')),
                ('malus', models.IntegerField(blank=True, default=None, null=True, verbose_name='Malus Armure')),
                ('echec_sort', models.IntegerField(blank=True, default=None, null=True, verbose_name="Taux en % de chance d'echecs de sort")),
                ('vitesse_deplacement', models.FloatField(blank=True, default=None, max_length=2, null=True, verbose_name='Vitesse Déplacement avec armure')),
                ('poids', models.IntegerField(blank=True, default=None, null=True, verbose_name="Poids de l'armure en livres")),
                ('discretion', models.BooleanField(blank=True, default=None, null=True, verbose_name='Armure discrète ?')),
            ],
        ),
        migrations.CreateModel(
            name='Bourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieces_platine', models.IntegerField(blank=True, default=None, null=True, verbose_name='Pièces de platine')),
                ('pieces_or', models.IntegerField(blank=True, default=None, null=True, verbose_name="Pièces d'or")),
                ('pieces_electrum', models.IntegerField(blank=True, default=None, null=True, verbose_name="Pièces d'électrum")),
                ('pieces_argent', models.IntegerField(blank=True, default=None, null=True, verbose_name="Pièces d'argent")),
                ('pieces_cuivre', models.IntegerField(blank=True, default=None, null=True, verbose_name='Pièces de cuivre')),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristiques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force', models.IntegerField(verbose_name='Force')),
                ('dexterite', models.IntegerField(verbose_name='Dexterité')),
                ('constitution', models.IntegerField(verbose_name='Constitution')),
                ('intelligence', models.IntegerField(verbose_name='Intelligence')),
                ('sagesse', models.IntegerField(verbose_name='Sagesse')),
                ('charisme', models.IntegerField(verbose_name='Charisme')),
            ],
        ),
        migrations.CreateModel(
            name='Competences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acrobaties', models.IntegerField(verbose_name='Acrobaties (DEX)')),
                ('Arcanes', models.IntegerField(verbose_name='Arcanes (INT)')),
                ('Athletisme', models.IntegerField(verbose_name='Athletisme (FOR)')),
                ('Discretion', models.IntegerField(verbose_name='Discretion (DEX)')),
                ('Dressage', models.IntegerField(verbose_name='Dressage (SAG)')),
                ('Escamotage', models.IntegerField(verbose_name='Escamotage (DEX)')),
                ('Histoire', models.IntegerField(verbose_name='Histoire (INT)')),
                ('Intimidation', models.IntegerField(verbose_name='Intimidation (CHA)')),
                ('Investigation', models.IntegerField(verbose_name='Investigation (INT)')),
                ('Medecine', models.IntegerField(verbose_name='Medecine (SAG)')),
                ('Nature', models.IntegerField(verbose_name='Nature (INT)')),
                ('Perception', models.IntegerField(verbose_name='Perception (SAG)')),
                ('Perspicacite', models.IntegerField(verbose_name='Perspicacite (SAG)')),
                ('Persusasion', models.IntegerField(verbose_name='Persusasion (CHA)')),
                ('Religion', models.IntegerField(verbose_name='Religion (INT)')),
                ('Representation', models.IntegerField(verbose_name='Representation (CHA)')),
                ('Survie', models.IntegerField(verbose_name='Survie (SAG)')),
                ('Tromperie', models.IntegerField(verbose_name='Tromperie (CHA)')),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armes', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Adventures.Arme')),
                ('armure', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Adventures.Armure')),
                ('bourse', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Adventures.Bourse')),
            ],
        ),
        migrations.CreateModel(
            name='Objet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=None, max_length=255, null=True, verbose_name="Nom de l'objet")),
                ('prix', models.IntegerField(blank=True, default=None, null=True, verbose_name="Prix de l'objet")),
                ('poids', models.IntegerField(blank=True, default=None, null=True, verbose_name="Poids de l'objet")),
            ],
        ),
        migrations.CreateModel(
            name='Outil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=None, max_length=255, null=True, verbose_name="Nom de l'outil")),
                ('prix', models.IntegerField(blank=True, default=None, null=True, verbose_name="Prix de l'outil")),
                ('poids', models.IntegerField(blank=True, default=None, null=True, verbose_name="Poids de l'outil")),
            ],
        ),
        migrations.CreateModel(
            name='Physique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('taille', models.FloatField(verbose_name='Taille')),
                ('categorie_taille', models.CharField(default=None, max_length=2, verbose_name='Catégorie de taille')),
                ('poids', models.IntegerField(verbose_name='Poids')),
                ('yeux', models.IntegerField(verbose_name='Yeux')),
                ('peau', models.IntegerField(verbose_name='Peau')),
                ('cheveux', models.IntegerField(verbose_name='Cheveux')),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True, unique=True, verbose_name='Nom')),
                ('race', models.CharField(max_length=100, verbose_name='Race')),
                ('classe', models.CharField(max_length=100, verbose_name='Classe')),
                ('pv', models.IntegerField(verbose_name='Points de vie')),
                ('level', models.IntegerField(verbose_name='Niveau')),
                ('ca', models.IntegerField(default=None, verbose_name="Classe d'armure")),
                ('vitesse_deplacement', models.FloatField(default=None, max_length=2, verbose_name='Vitesse de déplacement')),
                ('fonction', models.CharField(choices=[('Marchand', 'Marchand'), ('Quête', 'Quete'), ('Discussion', 'Discussion')], default='Discussion', max_length=100, verbose_name='Fonction du PNJ')),
                ('caracteristiques', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Adventures.Caracteristiques')),
                ('competences', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Adventures.Competences')),
                ('equipement', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Adventures.Equipement')),
                ('physique', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Adventures.Physique')),
            ],
        ),
        migrations.AddField(
            model_name='equipement',
            name='objets',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Adventures.Objet'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='outils',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Adventures.Outil'),
        ),
        migrations.CreateModel(
            name='Ennemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True, unique=True, verbose_name='Nom')),
                ('race', models.CharField(max_length=100, verbose_name='Race')),
                ('classe', models.CharField(max_length=100, verbose_name='Classe')),
                ('pv', models.IntegerField(verbose_name='Points de vie')),
                ('level', models.IntegerField(verbose_name='Niveau')),
                ('ca', models.IntegerField(default=None, verbose_name="Classe d'armure")),
                ('vitesse_deplacement', models.FloatField(default=None, max_length=2, verbose_name='Vitesse de déplacement')),
                ('fonction', models.CharField(choices=[('Sbire', 'Sbire'), ('Capitaine', 'Capitaine'), ('Boss', 'Boss')], default='Sbire', max_length=100, verbose_name="Fonction de l'ennemi")),
                ('caracteristiques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adventures.Caracteristiques')),
                ('competences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adventures.Competences')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adventures.Equipement')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True, unique=True, verbose_name='Nom')),
                ('alignement', models.CharField(max_length=100, null=True, unique=True, verbose_name='Alignement')),
                ('race', models.CharField(max_length=100, verbose_name='Race')),
                ('classe', models.CharField(max_length=100, verbose_name='Classe')),
                ('pv_actuels', models.IntegerField(verbose_name="Points de vie à l'instanté")),
                ('pv_temporaires', models.IntegerField(verbose_name='Points de vie temporaires')),
                ('level', models.IntegerField(verbose_name='Niveau')),
                ('xp', models.IntegerField(blank=True, default=None, verbose_name='Experience')),
                ('bonus_maitrise', models.IntegerField(default=None, verbose_name='Bonus de maitrîse')),
                ('ca', models.IntegerField(default=None, verbose_name="Classe d'armure")),
                ('initiative', models.IntegerField(default=None, verbose_name='Initiative')),
                ('vitesse_deplacement', models.FloatField(default=None, max_length=2, verbose_name='Vitesse de déplacement')),
                ('caracteristiques', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Adventures.Caracteristiques')),
                ('competences', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Adventures.Competences')),
                ('equipement', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Adventures.Equipement')),
                ('physique', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Adventures.Physique')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
