# Generated by Django 3.0.2 on 2020-01-24 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.IntegerField(blank=True, default=None, max_length=5, null=True, verbose_name="Prix de l'arme")),
            ],
        ),
        migrations.CreateModel(
            name='Armure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.IntegerField(blank=True, default=None, max_length=5, null=True, verbose_name="Prix de l'armure")),
                ('ca_bonus', models.IntegerField(blank=True, default=None, max_length=2, null=True, verbose_name='CA Bonus')),
                ('max_dex', models.IntegerField(blank=True, default=None, max_length=2, null=True, verbose_name='Maximum Dextérité')),
                ('malus', models.IntegerField(blank=True, default=None, max_length=2, null=True, verbose_name='Malus Armure')),
                ('echec_sort', models.IntegerField(blank=True, default=None, max_length=2, null=True, verbose_name="Taux en % de chance d'echecs de sort")),
                ('vitesse_deplacement', models.FloatField(blank=True, default=None, max_length=2, null=True, verbose_name='Vitesse Déplacement avec armure')),
                ('poids', models.IntegerField(blank=True, default=None, max_length=2, null=True, verbose_name="Poids de l'armure en livres")),
            ],
        ),
        migrations.CreateModel(
            name='Bouclier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.IntegerField(blank=True, default=None, max_length=5, null=True, verbose_name='Prix du bouclier')),
            ],
        ),
        migrations.CreateModel(
            name='Bourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieces_platine', models.IntegerField(blank=True, default=None, max_length=3, null=True, verbose_name='Pièces de platine')),
                ('pieces_or', models.IntegerField(blank=True, default=None, max_length=3, null=True, verbose_name="Pièces d'or")),
                ('pieces_electrum', models.IntegerField(blank=True, default=None, max_length=3, null=True, verbose_name="Pièces d'électrum")),
                ('pieces_argent', models.IntegerField(blank=True, default=None, max_length=3, null=True, verbose_name="Pièces d'argent")),
                ('pieces_cuivre', models.IntegerField(blank=True, default=None, max_length=3, null=True, verbose_name='Pièces de cuivre')),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristiques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force', models.IntegerField(max_length=3, verbose_name='Force')),
                ('dexterite', models.IntegerField(max_length=3, verbose_name='Points de vie')),
                ('constitution', models.IntegerField(max_length=3, verbose_name='Points de vie')),
                ('intelligence', models.IntegerField(max_length=3, verbose_name='Points de vie')),
                ('sagesse', models.IntegerField(max_length=3, verbose_name='Points de vie')),
                ('charisme', models.IntegerField(max_length=3, verbose_name='Points de vie')),
            ],
        ),
        migrations.CreateModel(
            name='Competences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acrobaties', models.IntegerField(max_length=3, verbose_name='Acrobaties (DEX)')),
                ('Arcanes', models.IntegerField(max_length=3, verbose_name='Arcanes (INT)')),
                ('Athletisme', models.IntegerField(max_length=3, verbose_name='Athletisme (FOR)')),
                ('Discretion', models.IntegerField(max_length=3, verbose_name='Discretion (DEX)')),
                ('Dressage', models.IntegerField(max_length=3, verbose_name='Dressage (SAG)')),
                ('Escamotage', models.IntegerField(max_length=3, verbose_name='Escamotage (DEX)')),
                ('Histoire', models.IntegerField(max_length=3, verbose_name='Histoire (INT)')),
                ('Intimidation', models.IntegerField(max_length=3, verbose_name='Intimidation (CHA)')),
                ('Investigation', models.IntegerField(max_length=3, verbose_name='Investigation (INT)')),
                ('Medecine', models.IntegerField(max_length=3, verbose_name='Medecine (SAG)')),
                ('Nature', models.IntegerField(max_length=3, verbose_name='Nature (INT)')),
                ('Perception', models.IntegerField(max_length=3, verbose_name='Perception (SAG)')),
                ('Perspicacite', models.IntegerField(max_length=3, verbose_name='Perspicacite (SAG)')),
                ('Persusasion', models.IntegerField(max_length=3, verbose_name='Persusasion (CHA)')),
                ('Religion', models.IntegerField(max_length=3, verbose_name='Religion (INT)')),
                ('Representation', models.IntegerField(max_length=3, verbose_name='Representation (CHA)')),
                ('Survie', models.IntegerField(max_length=3, verbose_name='Survie (SAG)')),
                ('Tromperie', models.IntegerField(max_length=3, verbose_name='Tromperie (CHA)')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adventures.Arme')),
                ('armure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adventures.Armure')),
                ('bouclier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adventures.Bouclier')),
                ('bourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adventures.Bourse')),
            ],
        ),
        migrations.CreateModel(
            name='Physique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(max_length=2, verbose_name='Age')),
                ('taille', models.FloatField(max_length=3, verbose_name='Taille')),
                ('poids', models.IntegerField(max_length=2, verbose_name='Poids')),
                ('yeux', models.IntegerField(max_length=2, verbose_name='Yeux')),
                ('peau', models.IntegerField(max_length=2, verbose_name='Peau')),
                ('cheveux', models.IntegerField(max_length=2, verbose_name='Cheveux')),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='Nom')),
                ('race', models.CharField(max_length=100, verbose_name='Race')),
                ('classe', models.CharField(max_length=100, verbose_name='Classe')),
                ('pv', models.IntegerField(max_length=4, verbose_name='Points de vie')),
                ('level', models.IntegerField(max_length=3, verbose_name='Niveau')),
                ('ca', models.IntegerField(default=None, max_length=3, verbose_name="Classe d'armure")),
                ('vitesse_deplacement', models.FloatField(default=None, max_length=2, verbose_name='Vitesse de déplacement')),
                ('fonction', models.CharField(choices=[('Marchand', 'Marchand'), ('Quête', 'Quete'), ('Discussion', 'Discussion')], default='Discussion', max_length=100, verbose_name='Fonction du PNJ')),
                ('caracteristiques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adventures.Caracteristiques')),
                ('competences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adventures.Competences')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adventures.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Ennemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='Nom')),
                ('race', models.CharField(max_length=100, verbose_name='Race')),
                ('classe', models.CharField(max_length=100, verbose_name='Classe')),
                ('pv', models.IntegerField(max_length=4, verbose_name='Points de vie')),
                ('level', models.IntegerField(max_length=3, verbose_name='Niveau')),
                ('ca', models.IntegerField(default=None, max_length=3, verbose_name="Classe d'armure")),
                ('vitesse_deplacement', models.FloatField(default=None, max_length=2, verbose_name='Vitesse de déplacement')),
                ('fonction', models.CharField(choices=[('Sbire', 'Sbire'), ('Capitaine', 'Capitaine'), ('Boss', 'Boss')], default='Sbire', max_length=100, verbose_name="Fonction de l'ennemi")),
                ('caracteristiques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adventures.Caracteristiques')),
                ('competences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adventures.Competences')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adventures.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='Nom')),
                ('alignement', models.CharField(max_length=100, null=True, unique=True, verbose_name='Alignement')),
                ('race', models.CharField(max_length=100, verbose_name='Race')),
                ('classe', models.CharField(max_length=100, verbose_name='Classe')),
                ('pv_actuels', models.IntegerField(max_length=4, verbose_name="Points de vie à l'instanté")),
                ('pv_temporaires', models.IntegerField(max_length=4, verbose_name='Points de vie temporaires')),
                ('level', models.IntegerField(max_length=3, verbose_name='Niveau')),
                ('xp', models.IntegerField(blank=True, default=None, max_length=5, verbose_name='Experience')),
                ('bonus_maitrise', models.IntegerField(default=None, max_length=3, verbose_name='Bonus de maitrîse')),
                ('ca', models.IntegerField(default=None, max_length=3, verbose_name="Classe d'armure")),
                ('initiative', models.IntegerField(default=None, max_length=3, verbose_name='Initiative')),
                ('vitesse_deplacement', models.FloatField(default=None, max_length=2, verbose_name='Vitesse de déplacement')),
                ('caracteristiques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adventures.Caracteristiques')),
                ('competences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adventures.Competences')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adventures.Equipment')),
                ('physique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adventures.Physique')),
            ],
        ),
    ]
