# Generated by Django 3.0.2 on 2020-01-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adventures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arme',
            name='type_armure',
        ),
        migrations.AddField(
            model_name='arme',
            name='type_arme',
            field=models.CharField(choices=[('Armes courantes de corps à corps', 'Courantes Cac'), ('Armes courantes à distance', 'Courantes Dist'), ('Armes de guerre de corps à corps', 'Guerre Cac'), ('Armes de guerre à distance', 'Guerre Dist')], default='Armes courantes de corps à corps', max_length=100, verbose_name="Type de l'arme"),
        ),
        migrations.AddField(
            model_name='arme',
            name='type_degats',
            field=models.CharField(choices=[('1', 'Contondant'), ('2', 'Perforant'), ('3', 'Tranchant')], default='1', max_length=100, verbose_name="Type de dégâts de l'arme"),
        ),
    ]
