# Generated by Django 3.0.2 on 2020-01-25 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adventures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='arme',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='armure',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='bouclier',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='bourse',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='objets',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='outils',
        ),
        migrations.AddField(
            model_name='arme',
            name='type_armure',
            field=models.CharField(choices=[('1', 'Armes courantes de corps à corps'), ('2', 'Armes courantes à distance'), ('3', 'Armes de guerre de corps à corps'), ('4', 'Armes de guerre à distance')], default=None, max_length=100, verbose_name="Type de l'arme"),
        ),
        migrations.RenameModel(
            old_name='Objets',
            new_name='Objet',
        ),
        migrations.RenameModel(
            old_name='Outils',
            new_name='Outil',
        ),
        migrations.DeleteModel(
            name='Bouclier',
        ),
        migrations.AddField(
            model_name='equipement',
            name='armes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Adventures.Arme'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='armure',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Adventures.Armure'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='bourse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Adventures.Bourse'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='objets',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Adventures.Objet'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='outils',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Adventures.Outil'),
        ),
        migrations.AlterField(
            model_name='character',
            name='equipement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Adventures.Equipement'),
        ),
        migrations.AlterField(
            model_name='ennemy',
            name='equipement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adventures.Equipement'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='equipement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Adventures.Equipement'),
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
