# Generated by Django 3.0.2 on 2020-01-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adventures', '0003_armure_type_armure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armure',
            name='type_armure',
            field=models.CharField(choices=[('1', 'Armure légère'), ('2', 'Armure intermédiaire'), ('3', 'Armure lourde')], default=None, max_length=100, verbose_name="Type de l'armure"),
        ),
    ]
