# Generated by Django 3.0.2 on 2020-01-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adventures', '0004_auto_20200125_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouclier',
            name='nom',
            field=models.CharField(default=None, max_length=100, verbose_name='Nom du bouclier'),
        ),
    ]
