# Generated by Django 3.0.2 on 2020-01-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adventures', '0005_bouclier_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouclier',
            name='nom',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Nom du bouclier'),
        ),
    ]
